[package]
name = "account-login"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["cookies"] }

[dev-dependencies]
tokio = { version = "1.43.0", features = ["full"] }
