[package]
name = "database-access"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.8.2", features = ["runtime-tokio", "mysql", "macros", "derive"] }
tokio = { version = "1.41.1", features = ["full"] }

[dev-dependencies]
dotenvy = { version = "0.15.7" }